# use Node.js as basic image
FROM node:18-alpine AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
# RUN npm install react-router-dom

# copy code but except tests
COPY . .
# RUN rm -rf src/**/*.test.tsx
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]

# use Nginx as frontend server
# FROM nginx:alpine
# COPY --from=build /app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

